# Generated by Django 5.1.4 on 2025-01-10 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('credit_card_number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator('^\\d{16,19}$', 'Kredit karta raqami faqat 16-19 raqamdan iborat bo‘lishi kerak')])),
                ('expiry_date', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{2}/\\d{2}$', 'Format MM/YY bo‘lishi kerak')])),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', 'CVV faqat 3 yoki 4 raqamdan iborat bo‘lishi kerak')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='checkout_or_created_018c23_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
    ]
