# Generated by Django 5.1.4 on 2025-01-12 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='credit_card_number',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator('^\\d{16,19}$', 'Credit card number must be 16-19 digits only')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='cvv',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', 'CVV should be 3 or 4 digits only')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{2}/\\d{2}$', 'Format should be MM/YY')]),
        ),
    ]
